<?xml version="1.0" encoding="utf-8" ?>
<odoo noupdate="1">
    <!-- Error Email template  -->
    <record id="scheduler_error_mailer" model="mail.template">
        <field name="name">Scheduler Error</field>
        <field name="email_from">{{object.user_id.email or ''}}</field>
        <field name="email_to">{{object.user_id.email or ''}}</field>
        <field
            name="subject"
        >[DB {{ctx.get('dbname')}}] Scheduler '{{object.name or ''}}' FAILED</field>
        <field name="model_id" ref="base.model_ir_cron" />
        <field name="auto_delete" eval="True" />
        <field name="body_html">
                <![CDATA[
<div style="font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; ">

<p>Odoo tried to run the scheduler <em><t t-out="object.name or ''"/></em> in the database <em><t t-out="ctx.get('dbname')"/></em> but it failed. Here is the error message :</p>

<strong>
<t t-out="ctx.get('job_exception') or 'Failed to get the error message from the context.'"/>
</strong>

<p>You may check the logs of the Odoo server to get more information about this failure.</p>

<p>Properties of the scheduler <em><t t-out="object.name or ''"/></em> :</p>
<ul>
<li>Model : <t t-out="object.model_id.name or ''"/></li>
<li>Python code : <code><t t-out="object.code or ''"/></code></li>
<li>Interval : <t t-out="object.interval_number or '0'"/> <t t-out="object.interval_type or ''"/></li>
<li>Number of calls : <t t-out="object.numbercall or '0'"/></li>
<li>Repeat missed : <t t-out="object.doall"/></li>
<li>User : <t t-out="object.user_id.name or ''"/></li>
</ul>

<p>
-- <br/>
Automatic e-mail sent by Odoo. Do not reply.<br/>
Database : <t t-out="ctx.get('dbname')"/>
</p>
</div>
    ]]>
        </field>
    </record>
</odoo>
