# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* scheduler_error_mailer
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 13.0\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: 2023-06-09 16:09+0000\n"
"Last-Translator: Ignacio Buioli <ibuioli@gmail.com>\n"
"Language-Team: none\n"
"Language: es_AR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 4.17\n"

#. module: scheduler_error_mailer
#: model:mail.template,body_html:scheduler_error_mailer.scheduler_error_mailer
msgid ""
"\n"
"                \n"
"<div style=\"font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-"
"serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; \">\n"
"\n"
"<p>Odoo tried to run the scheduler <em><t t-out=\"object.name or ''\"/></em> "
"in the database <em><t t-out=\"ctx.get('dbname')\"/></em> but it failed. "
"Here is the error message :</p>\n"
"\n"
"<strong>\n"
"<t t-out=\"ctx.get('job_exception') or 'Failed to get the error message from "
"the context.'\"/>\n"
"</strong>\n"
"\n"
"<p>You may check the logs of the Odoo server to get more information about "
"this failure.</p>\n"
"\n"
"<p>Properties of the scheduler <em><t t-out=\"object.name or ''\"/></em> :</"
"p>\n"
"<ul>\n"
"<li>Model : <t t-out=\"object.model_id.name or ''\"/></li>\n"
"<li>Python code : <code><t t-out=\"object.code or ''\"/></code></li>\n"
"<li>Interval : <t t-out=\"object.interval_number or '0'\"/> <t t-out="
"\"object.interval_type or ''\"/></li>\n"
"<li>Number of calls : <t t-out=\"object.numbercall or '0'\"/></li>\n"
"<li>Repeat missed : <t t-out=\"object.doall\"/></li>\n"
"<li>User : <t t-out=\"object.user_id.name or ''\"/></li>\n"
"</ul>\n"
"\n"
"<p>\n"
"-- <br/>\n"
"Automatic e-mail sent by Odoo. Do not reply.<br/>\n"
"Database : <t t-out=\"ctx.get('dbname')\"/>\n"
"</p>\n"
"</div>\n"
"    \n"
"        "
msgstr ""
"\n"
"                \n"
"<div style=\"font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-"
"serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; \">\n"
"\n"
"<p>Odoo trató de ejecutar el planificador <em><t t-out=\"object.name or ''\"/"
"></em> en la base de datos <em><t t-out=\"ctx.get('dbname')\"/></em> pero "
"falló. Acá está el mensaje de error :</p>\n"
"\n"
"<strong>\n"
"<t t-out=\"ctx.get('job_exception') or 'Falló en obtener el mensaje de error "
"del contexto.'\"/>\n"
"</strong>\n"
"\n"
"<p>Puede consultar los registros del servidor Odoo para obtener más "
"información sobre esta falla.</p>\n"
"\n"
"<p>Propiedad del planificador <em><t t-out=\"object.name or ''\"/></em> :</"
"p>\n"
"<ul>\n"
"<li>Modelo : <t t-out=\"object.model_id.name or ''\"/></li>\n"
"<li>Código Python : <code><t t-out=\"object.code or ''\"/></code></li>\n"
"<li>Intervalo : <t t-out=\"object.interval_number or '0'\"/> <t t-out="
"\"object.interval_type or ''\"/></li>\n"
"<li>Número de ejecuciones : <t t-out=\"object.numbercall or '0'\"/></li>\n"
"<li>Repetir perdidos : <t t-out=\"object.doall\"/></li>\n"
"<li>Usuario : <t t-out=\"object.user_id.name or ''\"/></li>\n"
"</ul>\n"
"\n"
"<p>\n"
"-- <br/>\n"
"Email enviado automáticamente por Odoo. No responder.<br/>\n"
"Base de datos : <t t-out=\"ctx.get('dbname')\"/>\n"
"</p>\n"
"</div>\n"
"    \n"
"        "

#. module: scheduler_error_mailer
#: model:ir.model.fields,field_description:scheduler_error_mailer.field_ir_cron__email_template_id
msgid "Error E-mail Template"
msgstr "Plantilla de correo electrónico del error"

#. module: scheduler_error_mailer
#: model:ir.model,name:scheduler_error_mailer.model_ir_cron
msgid "Scheduled Actions"
msgstr "Acciones Automatizadas"

#. module: scheduler_error_mailer
#: model:mail.template,name:scheduler_error_mailer.scheduler_error_mailer
msgid "Scheduler Error"
msgstr "Error del Planificador"

#. module: scheduler_error_mailer
#: model:ir.model.fields,help:scheduler_error_mailer.field_ir_cron__email_template_id
msgid "Select the email template that will be sent when this scheduler fails."
msgstr ""
"Seleccione la plantilla de correo electrónico que se enviará cuando falla "
"este planificador."

#. module: scheduler_error_mailer
#: model:ir.model.fields,field_description:scheduler_error_mailer.field_ir_cron__smart_search
msgid "Smart Search"
msgstr "Búsqueda Inteligente"

#. module: scheduler_error_mailer
#. odoo-python
#: code:addons/scheduler_error_mailer/models/ir_cron.py:0
#, python-format
msgid "Task failure with UID = %d."
msgstr "Error de Tarea con UID = %d."

#. module: scheduler_error_mailer
#: model:ir.actions.server,name:scheduler_error_mailer.test_scheduler_error_mailer_ir_actions_server
#: model:ir.cron,cron_name:scheduler_error_mailer.test_scheduler_error_mailer
msgid "Test Scheduler Error Mailer"
msgstr "Probar el Mail de Errores del Planificador"

#. module: scheduler_error_mailer
#: model:mail.template,subject:scheduler_error_mailer.scheduler_error_mailer
msgid "[DB {{ctx.get('dbname')}}] Scheduler '{{object.name or ''}}' FAILED"
msgstr ""
"[DB {{ctx.get('dbname')}}] Planificador '{{object.name or ''}}' FALLIDO"

#~ msgid ""
#~ "\n"
#~ "                \n"
#~ "<div style=\"font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-"
#~ "serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; "
#~ "\">\n"
#~ "\n"
#~ "<p>Odoo tried to run the scheduler <em>${object.name or ''}</em> in the "
#~ "database <em>${ctx.get('dbname')}</em> but it failed. Here is the error "
#~ "message :</p>\n"
#~ "\n"
#~ "<strong>\n"
#~ "${ctx.get('job_exception') or 'Failed to get the error message from the "
#~ "context.'}\n"
#~ "</strong>\n"
#~ "\n"
#~ "<p>You may check the logs of the Odoo server to get more information "
#~ "about this failure.</p>\n"
#~ "\n"
#~ "<p>Properties of the scheduler <em>${object.name or ''}</em> :</p>\n"
#~ "<ul>\n"
#~ "<li>Model : ${object.model_id.name or ''}</li>\n"
#~ "<li>Python code : <code>${object.code or ''}</code></li>\n"
#~ "<li>Interval : ${object.interval_number or '0'} ${object.interval_type or "
#~ "''}</li>\n"
#~ "<li>Number of calls : ${object.numbercall or '0'}</li>\n"
#~ "<li>Repeat missed : ${object.doall}</li>\n"
#~ "<li>User : ${object.user_id.name or ''}</li>\n"
#~ "</ul>\n"
#~ "\n"
#~ "<p>\n"
#~ "-- <br/>\n"
#~ "Automatic e-mail sent by Odoo. Do not reply.<br/>\n"
#~ "Database : ${ctx.get('dbname')}\n"
#~ "</p>\n"
#~ "</div>\n"
#~ "    \n"
#~ "            "
#~ msgstr ""
#~ "\n"
#~ "                \n"
#~ "<div style=\"font-family: 'Lucida Grande', Ubuntu, Arial, Verdana, sans-"
#~ "serif; font-size: 12px; color: rgb(34, 34, 34); background-color: #FFF; "
#~ "\">\n"
#~ "\n"
#~ "<p>Odoo tried to run the scheduler <em>${object.name or ''}</em> en la "
#~ "base de datos <em>${ctx.get('dbname')}</em> pero falló. Acá está el "
#~ "mensaje de error:</p>\n"
#~ "\n"
#~ "<strong>\n"
#~ "${ctx.get('job_exception') or 'No se pudo obtener el mensaje de error del "
#~ "contexto.'}\n"
#~ "</strong>\n"
#~ "\n"
#~ "<p>Puede revisar los registros del servidor de Odoo para obtener más "
#~ "información acerca de este fallo.</p>\n"
#~ "\n"
#~ "<p>Propiedades del planificador <em>${object.name or ''}</em> :</p>\n"
#~ "<ul>\n"
#~ "<li>Modelo : ${object.model_id.name or ''}</li>\n"
#~ "<li>Código de Python : <code>${object.code or ''}</code></li>\n"
#~ "<li>Intervalo : ${object.interval_number or '0'} ${object.interval_type "
#~ "or ''}</li>\n"
#~ "<li>Número de llamados : ${object.numbercall or '0'}</li>\n"
#~ "<li>Repetir perdidos : ${object.doall}</li>\n"
#~ "<li>Usuario : ${object.user_id.name or ''}</li>\n"
#~ "</ul>\n"
#~ "\n"
#~ "<p>\n"
#~ "-- <br/>\n"
#~ "Email enviado automáticamente por Odoo. No responder.<br/>\n"
#~ "Base de datos : ${ctx.get('dbname')}\n"
#~ "</p>\n"
#~ "</div>\n"
#~ "    \n"
#~ "            "

#~ msgid "[DB ${ctx.get('dbname')}] Scheduler '${object.name or ''}' FAILED"
#~ msgstr "[DB ${ctx.get('dbname')}] Planificador '${object.name or ''}' FALLÓ"
